openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8000
    description: Generated server url
paths:
  /ordershistory:
    post:
      tags:
        - sync-controller
      operationId: sync
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderSyncRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderHistory'
components:
  schemas:
    OrderSyncRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerName:
          type: string
        courierName:
          type: string
        deliveryStatus:
          type: string
        products:
          type: array
          items:
            type: string
        totalPrice:
          type: number
    OrderHistory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerName:
          type: string
        courierName:
          type: string
        deliveryStatus:
          type: string
        productNames:
          type: string
        totalPrice:
          type: number
